# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 'TermHub'
subtitle: 'Termux Tools & Linux Commands Tutorial'
description: 'TermHub empowers you to unlock the full potential of your Android device with comprehensive tutorials and resources on Termux tools, Linux commands, and other powerful tools. Level up your skills, automate tasks, and explore the command line like a pro.'
keywords: 'Termux, Android, Linux, CLI, commands, tools, tutorials, hacking, automation, security, privacy, root, developers, makers, programmers, power users, community'
author: 'Viliyam Vasava'
language: en
timezone: 'Asia/Kolkata'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://yeshugit.netlify.app/
permalink: /post/:slug/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: wnloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: false
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: prismjs
highlight:
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  prismjs_line_number: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: '/blog'
  per_page: 10
  order_by: -date


# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD MMMM, YYYY
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
search:
  path: search.json
  field: post
  content: true
## Themes: https://hexo.io/themes/
theme: easymux

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
  
# New Template
