appletouchicon: '/apple-touch-icon.png'
favicon32: '/favicon-32x32.png'
favicon16: '/favicon-16x16.png'
webmanifest: '/site.webmanifest'
featured_img: '/img/post/default-featured.webp'
header_img: '/img/header.webp'